/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "asyncset.v:2.1-12.10" *)
module asyncset(clk, d, aset, q);
  (* src = "asyncset.v:3.13-3.17" *)
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "asyncset.v:3.13-3.17" *)
  input aset;
  wire aset;
  (* src = "asyncset.v:3.7-3.10" *)
  input clk;
  wire clk;
  (* src = "asyncset.v:3.11-3.12" *)
  input d;
  wire d;
  (* src = "asyncset.v:4.12-4.13" *)
  output q;
  wire q;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_0_),
    .Y(_1_)
  );
  (* src = "asyncset.v:5.1-11.4" *)
  sky130_fd_sc_hd__dfstp_2 _4_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .SET_B(_2_)
  );
  assign _0_ = aset;
  assign _2_ = _1_;
endmodule
