/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "bad_mux.v:1.1-11.10" *)
module bad_mux(i0, i1, s, y);
  (* src = "bad_mux.v:2.7-2.9" *)
  wire _0_;
  (* src = "bad_mux.v:2.10-2.12" *)
  wire _1_;
  (* src = "bad_mux.v:2.13-2.14" *)
  wire _2_;
  (* src = "bad_mux.v:3.12-3.13" *)
  wire _3_;
  (* src = "bad_mux.v:2.7-2.9" *)
  input i0;
  wire i0;
  (* src = "bad_mux.v:2.10-2.12" *)
  input i1;
  wire i1;
  (* src = "bad_mux.v:2.13-2.14" *)
  input s;
  wire s;
  (* src = "bad_mux.v:3.12-3.13" *)
  output y;
  wire y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_2_),
    .X(_3_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _2_ = s;
  assign y = _3_;
endmodule
