/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "counter_opt1.v:1.1-13.10" *)
module counter_opt1(clk, reset, q);
  (* src = "counter_opt1.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _0_;
  wire _1_;
  (* src = "counter_opt1.v:2.11-2.16" *)
  wire _2_;
  (* src = "counter_opt1.v:1.40-1.45" *)
  wire _3_;
  (* force_downto = 32'd1 *)
  (* src = "counter_opt1.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2" *)
  wire [2:0] _4_;
  wire _5_;
  (* src = "counter_opt1.v:1.28-1.31" *)
  input clk;
  wire clk;
  (* src = "counter_opt1.v:2.11-2.16" *)
  (* unused_bits = "1 2" *)
  wire [2:0] count;
  (* src = "counter_opt1.v:1.55-1.56" *)
  output q;
  wire q;
  (* src = "counter_opt1.v:1.40-1.45" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(_2_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(_3_),
    .Y(_1_)
  );
  (* src = "counter_opt1.v:5.1-11.4" *)
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(_4_[0]),
    .Q(count[0]),
    .RESET_B(_5_)
  );
  assign _4_[2:1] = count[2:1];
  assign q = count[0];
  assign _2_ = count[0];
  assign _4_[0] = _0_;
  assign _3_ = reset;
  assign _5_ = _1_;
endmodule
