/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "dff_const3.v:1.1-18.10" *)
module dff_const3(clk, reset, q);
  wire _0_;
  wire _1_;
  (* src = "dff_const3.v:1.36-1.41" *)
  wire _2_;
  wire _3_;
  wire _4_;
  (* src = "dff_const3.v:1.25-1.28" *)
  input clk;
  wire clk;
  (* src = "dff_const3.v:1.54-1.55" *)
  output q;
  wire q;
  (* src = "dff_const3.v:2.5-2.7" *)
  wire q1;
  (* src = "dff_const3.v:1.36-1.41" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(_2_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(_2_),
    .Y(_1_)
  );
  (* src = "dff_const3.v:4.1-16.4" *)
  sky130_fd_sc_hd__dfstp_2 _7_ (
    .CLK(clk),
    .D(q1),
    .Q(q),
    .SET_B(_3_)
  );
  (* src = "dff_const3.v:4.1-16.4" *)
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(1'h1),
    .Q(q1),
    .RESET_B(_4_)
  );
  assign _2_ = reset;
  assign _3_ = _0_;
  assign _4_ = _1_;
endmodule
