/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "multipe_modules_opt.v:12.1-22.10" *)
module multiple_modules_opt(a, b, c, d, y);
  wire _0_;
  (* src = "multipe_modules_opt.v:12.45-12.46" *)
  wire _1_;
  (* src = "multipe_modules_opt.v:12.55-12.56" *)
  wire _2_;
  (* src = "multipe_modules_opt.v:13.6-13.8" *)
  wire _3_;
  (* src = "multipe_modules_opt.v:12.76-12.77" *)
  wire _4_;
  (* src = "multipe_modules_opt.v:12.35-12.36" *)
  input a;
  wire a;
  (* src = "multipe_modules_opt.v:12.45-12.46" *)
  input b;
  wire b;
  (* src = "multipe_modules_opt.v:12.55-12.56" *)
  input c;
  wire c;
  (* src = "multipe_modules_opt.v:12.65-12.66" *)
  input d;
  wire d;
  (* src = "multipe_modules_opt.v:13.6-13.8" *)
  wire n1;
  (* src = "multipe_modules_opt.v:12.76-12.77" *)
  output y;
  wire y;
  sky130_fd_sc_hd__a21o_1 _5_ (
    .A1(_3_),
    .A2(_1_),
    .B1(_2_),
    .X(_4_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "multipe_modules_opt.v:15.12-15.25" *)
  submodule1 sub1 (
    .a(a),
    .b(1'h1),
    .y(n1)
  );
  assign _3_ = n1;
  assign _1_ = b;
  assign _2_ = c;
  assign y = _4_;
endmodule

(* src = "multipe_modules_opt.v:2.1-4.10" *)
module submodule1(a, b, y);
  (* src = "multipe_modules_opt.v:2.25-2.26" *)
  wire _0_;
  (* src = "multipe_modules_opt.v:2.35-2.36" *)
  wire _1_;
  (* src = "multipe_modules_opt.v:2.46-2.47" *)
  wire _2_;
  (* src = "multipe_modules_opt.v:2.25-2.26" *)
  input a;
  wire a;
  (* src = "multipe_modules_opt.v:2.35-2.36" *)
  input b;
  wire b;
  (* src = "multipe_modules_opt.v:2.46-2.47" *)
  output y;
  wire y;
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
