/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "mux.v:3.1-12.10" *)
module mux(i0, i1, s, y);
  (* src = "mux.v:4.7-4.9" *)
  wire _0_;
  (* src = "mux.v:4.10-4.12" *)
  wire _1_;
  (* src = "mux.v:4.13-4.14" *)
  wire _2_;
  (* src = "mux.v:5.12-5.13" *)
  wire _3_;
  (* src = "mux.v:4.7-4.9" *)
  input i0;
  wire i0;
  (* src = "mux.v:4.10-4.12" *)
  input i1;
  wire i1;
  (* src = "mux.v:4.13-4.14" *)
  input s;
  wire s;
  (* src = "mux.v:5.12-5.13" *)
  output y;
  wire y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_2_),
    .X(_3_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _2_ = s;
  assign y = _3_;
endmodule
