/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "opt_check1.v:2.1-4.10" *)
module opt_check1(a, b, y);
  (* src = "opt_check1.v:2.26-2.27" *)
  wire _0_;
  (* src = "opt_check1.v:2.36-2.37" *)
  wire _1_;
  (* src = "opt_check1.v:2.47-2.48" *)
  wire _2_;
  (* src = "opt_check1.v:2.26-2.27" *)
  input a;
  wire a;
  (* src = "opt_check1.v:2.36-2.37" *)
  input b;
  wire b;
  (* src = "opt_check1.v:2.47-2.48" *)
  output y;
  wire y;
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
