/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "multiple_modules.v:7.1-11.10" *)
module submodule2(a, b, y);
  (* src = "multiple_modules.v:8.7-8.8" *)
  wire _0_;
  (* src = "multiple_modules.v:8.9-8.10" *)
  wire _1_;
  (* src = "multiple_modules.v:9.8-9.9" *)
  wire _2_;
  (* src = "multiple_modules.v:8.7-8.8" *)
  input a;
  wire a;
  (* src = "multiple_modules.v:8.9-8.10" *)
  input b;
  wire b;
  (* src = "multiple_modules.v:9.8-9.9" *)
  output y;
  wire y;
  sky130_fd_sc_hd__or2_0 _3_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
