#!/bin/tcsh -f

echo 
echo
echo "VVVVV                 VVVVV     IIIIIIIIIIIIIIIIIIIIIIIII   VVVVV                 VVVVV     EEEEEEEEEEEEEEEEEEEEEE     KKKKK            KKKKK "
echo " VVVVV               VVVVV      IIIIIIIIIIIIIIIIIIIIIIIII    VVVVV               VVVVV      EEEEEEEEEEEEEEEEEEEEEE     KKKKK           KKKKK  "
echo "  VVVVV             VVVVV               IIIII                 VVVVV             VVVVV       EEEEE                      KKKKK          KKKKK   "
echo "   VVVVV           VVVVV                IIIII                  VVVVV           VVVVV        EEEEE                      KKKKK         KKKKK    "
echo "    VVVVV         VVVVV			IIIII			VVVVV         VVVVV         EEEEE                      KKKKK        KKKKK     "
echo "     VVVVV       VVVVV 			IIIII			 VVVVV       VVVVV          EEEEE                      KKKKKKKKKK  KKKKK      "
echo "      VVVVV     VVVVV			IIIII                     VVVVV     VVVVV           EEEEEEEEEEEEEEEEEEEEEE     KKKKKKKKKKKKKKKK       "
echo "       VVVVV   VVVVV			IIIII                      VVVVV   VVVVV            EEEEEEEEEEEEEEEEEEEEEE     KKKKKKKKKKKKKKK        "
echo "        VVVVV VVVVV			IIIII                       VVVVV VVVVV             EEEEE                      KKKKKKKKK  KKKKK       "
echo "         VVVVVVVVV	                IIIII                        VVVVVVVVV              EEEEE                      KKKKK       KKKKK      "
echo "          VVVVVVV		        IIIII                         VVVVVVV               EEEEE                      KKKKK        KKKKK     "
echo "           VVVVV		        IIIII                          VVVVV                EEEEE                      KKKKK         KKKKK    "
echo "            VVV		      IIIIIIIIIIIIIIIIIIIIIIIII                 VVV                 EEEEEEEEEEEEEEEEEEEEEE     KKKKK          KKKKK   "
echo "             V		      IIIIIIIIIIIIIIIIIIIIIIIII                  V                  EEEEEEEEEEEEEEEEEEEEEE     KKKKK           KKKKK  "
echo 
echo
echo " 						      Please look into errors.txt to find the solution for frequently occuring errors		      "
echo "                                          Incase of any new error and if you find the solution, feel free to update it in errors.txt            "
echo " 						                 For further assistance mail@pesug20ec109@pesu.pes.edu                                "
echo 
echo


set my_work_dir = 'pwd'

if ( $#argv != 1)then
	echo "Error : Please provide run_ubuntu.sh or run_fedora.sh as the input"
	exit 1
endif 

if(! -f $argv[1] ) then
	echo "Error : The file does not exist or check if the name "$argv[1]" is correct. Exiting........"
	exit 1
else   
        chmod +x run.tcl
	chmod +x $argv[1]	
	tclsh run.tcl $argv[1]

endif


